import raw from './data/turkey.json';

/** A closed outline in projected kilometres (east is +x, north is +y). */
export type Ring = readonly (readonly [number, number])[];

export interface MapBounds {
  readonly minX: number;
  readonly minY: number;
  readonly maxX: number;
  readonly maxY: number;
}

export interface MapData {
  readonly attribution: string;
  readonly bounds: MapBounds;
  readonly turkey: readonly Ring[];
  readonly turkeyCoarse: readonly Ring[];
  readonly neighbours: readonly Ring[];
  readonly lakes: Readonly<Record<string, Ring>>;
}

/** Generated by scripts/build-map-data.ts. */
export const mapData = raw as unknown as MapData;

/** SVG path for a set of rings. SVG's y axis points down, so north is negated. */
export function ringsToSvgPath(rings: readonly Ring[]): string {
  return rings.map((ring) => `M${ring.map(([x, y]) => `${x},${-y}`).join('L')}Z`).join('');
}
